apiVersion: v1
kind: Pod
metadata:
  name: passenger-service-pod
  labels:
    component: web
spec:
  containers:
    - name: passenger-service
      image: newarcher/bus-service
      ports:
        - containerPort: 3000